import Head from 'next/head';
import { ForwardedRef, forwardRef, useState } from 'react';
import DatePicker from 'react-datepicker';
import { AiFillCalendar } from 'react-icons/ai';
import { HiChevronLeft, HiChevronRight } from 'react-icons/hi';

import Layout from '../components/layouts/Layout';

import type { NextPageWithLayout } from 'next';

const CustomInput = forwardRef((props, ref: ForwardedRef<HTMLInputElement>) => (
  <div className="relative">
    <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
      <AiFillCalendar className="h-5 w-5 text-gray-500 dark:text-gray-400" />
    </div>
    <input
      {...props}
      ref={ref}
      type="text"
      className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 pl-10 text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600  dark:bg-gray-700 dark:text-white"
      placeholder="Select date"
      readOnly
    />
  </div>
));
CustomInput.displayName = 'CustomInput';

const Home: NextPageWithLayout = () => {
  const [eventDay, setEventDay] = useState(new Date(Date.now()));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="grow px-6 py-2">
        <div className="mx-auto max-w-2xl">
          <h1 className="pb-8 text-xl">
            <span className="pr-2 italic">X</span>営業日後は何日？
          </h1>
          <DatePicker
            locale="ja"
            selected={eventDay}
            onChange={day => day && setEventDay(day)}
            dateFormat="yyyy/MM/dd"
            previousMonthButtonLabel={
              <HiChevronLeft className="h-5 w-5 text-gray-600 dark:text-gray-200" />
            }
            nextMonthButtonLabel={
              <HiChevronRight className="h-5 w-5 text-gray-600 dark:text-gray-200" />
            }
            customInput={<CustomInput />}
          />
        </div>
      </main>
    </>
  );
};

Home.getLayout = page => <Layout>{page}</Layout>;

export default Home;
